[workspace]
members = ["osprei-gui", "osprei-execution", "osprei-storage"]
resolver = "2"

[workspace.dependencies]
log = "0.4"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
