[package]
name = "osprei-execution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docker-api = { version = "0.14.0" }
log = { workspace = true }
serde = { version = "*", features = ["derive"] }
