[package]
name = "osprei-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
osprei = { path = "../osprei" }

leptos = "0.3.0"
serde = { version = "1.0.160", features = ["derive"] }
log = "0.4"
wasm-logger = "0.2"
reqwasm = "0.5"

serde_json = "*"