[package]
name = "osprei-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
web-sys = "0.3.61"

gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"

log = "0.4"
wasm-logger = "0.2"