[package]
name = "osprei-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.2", features = ["runtime-tokio-rustls", "sqlite"] }
log = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.108"
